version: "3.8"
services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes: 
            - type: bind
              source: ./src
              target: /app/src
        environment: 
            - MONGO_APP_USER
            - MONGO_APP_PWD
        # Assure le démarrage de la dépendance
        depends_on:
            - db
        # Redémarre le service selon l'option spécifié
        restart: unless-stopped
    db:
        image: mongo
        volumes: 
            - type: volume
              source: mydb
              target: /data/db
        environment: 
            - MONGO_INITDB_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD
        restart: unless-stopped
volumes: 
    mydb:
        external: true