version: "3.8"
services:
    server:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes: 
            - type: bind
              source: ./src
              target: /app/src
    db:
        image: mongo
        volumes: 
            - type: volume
              source: mydb
              target: /data/db
volumes: 
    mydb:
        external: true